[tool.ruff]
target-version = "py312"
line-length = 140

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN401",
    "D401", # Ignore "Imperative Mood" statement for docstrings.
    "D100",
    "D101", # Public class docstrings
    "ERA001", #Ignore commented out code.
    "FIX002", # Ignore TODO's telling you to "fix them".
    "F401",
    "F402",
    "F403",
    "F405",
    "PERF203",
    "PLR",
    "RUF001",
    "RUF002", # The character U+2013 "–" could be confused with the ASCII character U+002d "-", which is more common in source code.
    "RUF009",
    "RUF052", # for filtering "local dummy variable is accessed" eg. - vars using `_`
    "SIM105",
    "TD003", # Ignore TODO's not having a link/url to an issue.
    "UP007",
    "UP034",
    "UP038",
    "UP045", # Type var `Optional[X]` vs `X | None`
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
combine-as-imports = true

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
parametrize-names-type = "tuple"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
pythonVersion = "3.12"
exclude = ["logs/**", "**/.venv/**", "**/.vscode-server/", "/usr/*"]
include = [""]
useLibraryCodeForTypes = true
reportIncompatibleMethodOverride = false
