name: changelog

on:
  push:
    branches: [development]

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Change directory
        run: |
          cd /home/runner/work/TPie-Plus/TPie-Plus/

      - name: Generate Changelog
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"
      - run: python ~/work/TPie-Plus/TPie-Plus/.github/workflows/scripts/gen_changelog.py $$
